# Generated by Django 5.1.4 on 2025-01-21 09:01

import json.decoder
import json.encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.PositiveIntegerField()),
                ('projects', models.JSONField(decoder=json.decoder.JSONDecoder, default=list, encoder=json.encoder.JSONEncoder, null=True)),
                ('courses', models.JSONField(decoder=json.decoder.JSONDecoder, default=list, encoder=json.encoder.JSONEncoder, null=True)),
                ('rewards', models.JSONField(decoder=json.decoder.JSONDecoder, default=list, encoder=json.encoder.JSONEncoder, null=True)),
                ('finish_words', models.TextField(default=None, null=True)),
                ('missions', models.JSONField(decoder=json.decoder.JSONDecoder, default=list, encoder=json.encoder.JSONEncoder, null=True)),
                ('done', models.BooleanField(default=False)),
                ('goals', models.ManyToManyField(default=None, null=True, to='goals.goal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
