# Generated by Django 5.1.4 on 2025-01-21 09:46

import json.decoder
import json.encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='missions',
            field=models.JSONField(decoder=json.decoder.JSONDecoder, default=list, encoder=json.encoder.JSONEncoder),
        ),
    ]
