# Generated by Django 5.1.4 on 2025-01-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_goal_missions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goals',
            field=models.ManyToManyField(to='goals.goal'),
        ),
    ]
