# Generated by Django 5.1.4 on 2025-01-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_goal_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goals',
            field=models.ManyToManyField(blank=True, to='goals.goal'),
        ),
    ]
