# Generated by Django 5.1.4 on 2025-05-18 03:48

import django.db.models.deletion
import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entertainment', '0008_entertainment_release_date'),
        ('goals', '0004_alter_goal_goals'),
        ('learning_tracker', '0003_course_progress'),
        ('missions', '0008_alter_list_date'),
        ('sessions_manager', '0004_alter_partition_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=110, null=True)),
                ('content', models.TextField()),
                ('drawn_content', models.TextField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to=notes.models.upload_file)),
                ('entertainment_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entertainment.entertainment')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.goal')),
                ('learning_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_tracker.course')),
                ('missions_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='missions.list')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions_manager.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
