# Generated by Django 5.1.4 on 2025-01-17 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('coursera', 'coursera'), ('youtube', 'youtube')], default=('coursera', 'coursera'), max_length=50)),
                ('link', models.TextField()),
                ('status', models.CharField(choices=[('current', 'current'), ('later', 'later'), ('done', 'done')], default=('current', 'current'), max_length=8)),
                ('image', models.TextField(null=True)),
                ('list', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('done', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_tracker.course')),
            ],
        ),
    ]
