# Generated by Django 5.1.4 on 2025-01-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
