# Generated by Django 5.1.4 on 2025-02-14 20:39

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=authentication.models.upload_pic),
        ),
    ]
