# Generated by Django 5.1.4 on 2025-03-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_accountsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='intro_parts_nav',
            field=models.BooleanField(default=False, verbose_name='Intro parts navigation'),
        ),
    ]
