# Generated by Django 5.1.4 on 2025-04-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_accountsettings_intro_parts_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='default_entertainment_type',
            field=models.CharField(choices=[('anime&manga', 'anime&manga'), ('game', 'game'), ('shows&movies', 'shows&movies'), ('other', 'other')], default='anime&manga', max_length=25, null=True),
        ),
    ]
