# Generated by Django 5.1.4 on 2025-04-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_accountsettings_default_entertainment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='open_sidenav',
            field=models.BooleanField(default=False, verbose_name='Open sidenav'),
        ),
    ]
