# Generated by Django 5.1.4 on 2025-01-20 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('goal', models.IntegerField(default=None, null=True)),
                ('reward', models.IntegerField(default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('project', models.PositiveIntegerField(default=None, null=True)),
                ('course', models.PositiveIntegerField(default=None, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('working', 'working'), ('done', 'done')], default='pending', max_length=15)),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='missions.list')),
            ],
        ),
    ]
