# Generated by Django 5.1.4 on 2025-01-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_list_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('working', 'working'), ('done', 'done')], default=('pending', 'pending'), max_length=15),
        ),
    ]
