# Generated by Django 5.1.4 on 2025-02-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_alter_mission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='goal',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
