# Generated by Django 5.1.4 on 2025-02-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_alter_list_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='course',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='project',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
