# Generated by Django 5.1.4 on 2025-02-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_alter_mission_course_alter_mission_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('working', 'working'), ('done', 'done')], default='pending', max_length=15),
        ),
    ]
