# Generated by Django 5.1.4 on 2025-04-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0007_alter_mission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateField(),
        ),
    ]
