# Generated by Django 5.1.4 on 2025-01-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partition',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='partition',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='partition',
            name='user',
        ),
        migrations.AlterField(
            model_name='partition',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
