# Generated by Django 5.1.4 on 2025-01-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_manager', '0002_remove_partition_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.PositiveIntegerField(),
        ),
    ]
