# Generated by Django 5.1.4 on 2025-01-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_manager', '0003_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partition',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
