# Generated by Django 5.1.4 on 2025-01-18 04:42

import json.decoder
import json.encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainment',
            name='genres',
            field=models.JSONField(decoder=json.decoder.JSONDecoder, default=[], encoder=json.encoder.JSONEncoder),
        ),
    ]
