# Generated by Django 5.1.4 on 2025-01-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0003_alter_entertainment_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainment',
            name='relatives',
            field=models.ManyToManyField(blank=True, to='entertainment.entertainment'),
        ),
    ]
