# Generated by Django 5.1.4 on 2025-01-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0004_alter_entertainment_relatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainment',
            name='mal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
