# Generated by Django 5.1.4 on 2025-01-18 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0005_entertainment_mal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainment',
            name='rate',
            field=models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='user_rate',
            field=models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
