# Generated by Django 5.1.4 on 2025-02-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0006_alter_entertainment_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainment',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
